### ISSUE TITLE
Consider making as_option public

### ISSUE THREAD

**Issue by rnleach** [llogiq/optional#31]
It would be nice to use in cases with pattern matching such as `if let Some(val) = val.as_option() {...}`. I think is flows better than `if let Some(val) = Option::from(val) {...}`.

However, the latter has the advantage that it will still work if I all of a sudden decide to drop in `Option` again instead of `Optioned`.

What do you think? I'd be happy to submit a PR if you think it's OK for the API.

**Comment by llogiq** [comment]
Couldn't you use `if let Some(val) = val.into() { .. }`? This looks even nicer if you ask me.

Also the correct name in my view would be `into_option`, because I think it would consume the original value, right?

**Comment by rnleach** [comment]
Yeah, you're right on both thanks. I'll close this and just use into.

**Comment by llogiq** [comment]
Thank you for bringing this up anyway, this may be a blind spot in the docs.

**Comment by rnleach** [comment]
After refactoring quite a bit of code I have that processes arrays/Vecs of `Optioned`, I think this is worth re-opening. There were a lot of places where the compiler could not infer the types for `some_val.into()` and I had to type a lot of `Into::<Option<f64>>::into(some_val)`.

Making `as_option` into `into_option` and making it public would read better, be shorter, and be just as clear I think.

**Comment by llogiq** [comment]
Does `.map(Option::from)` work for you?

**Comment by rnleach** [comment]
Nope. That just wraps the interior `f64` in an `Option` and returns an `Option<Option<f64>>`.

 Along that line of reasoning I did find this, which is weird to look at, but it works: `.map(|inner| inner)`. That seems surprising at first glance and the coder's intentions aren't as clear as an `.into_option()` method would be. 

What I'm really trying to do is convert between types `Optioned` and `Option`, which is where `From` and `Into` are idiomatic. But due to the limitations of type inference and generics the `Into` trait works inconsistently. The workarounds (so far) are either verbose or make the intention unclear.

**Comment by llogiq** [comment]
Ah, I see. For those cases `.into_option` would indeed make sense. I'll gladly accept a PR
