### ISSUE TITLE
Usability with iterators and more consistent API.

### ISSUE THREAD

**Issue by rnleach** [llogiq/optional#36]
I've been using this a lot in arrays/Vecs where I then process the arrays using iterators. Methods like `filter_map` and `scan` are really nice for this kind of processing. But they also work with `Option`s. 

I like to use the `and_then` and related methods of `Option` (and now `Optioned`) inside the closures for these iterator functions. However, with `Optioned` this doesn't work well because those methods don't return `Option`.

I noticed in the implementation of `map` for `Optioned` you chose to return an `Option` and then have a corresponding method `map_t` that stays within the `Optioned` type.  I think that is a good approach. But in response to issue #26 @CAD97 submitted PR #27 wherein the `or` method returned an `Optioned`. I think it should return an `Option` and then have another method `or_t` that returns and `Optioned` which is more inline with the way `map` and `map_t` were implemented. I think the same should be done for the `and` methods I submitted in a PR later.

@llogiq , @CAD97  what do you think?  

Of course I would be willing to put together the PR, but I would like to know if you are open to these changes in the API first.

Thanks,

**Comment by CAD97** [comment]
In the case of `or`, the two `T` are always the same, so staying within `Optioned` makes sense. If you need it as an `Option`, you can always `.into()`.

**Comment by rnleach** [comment]
True. But for the and methods that is not the case. For instance I'll use the `izip!` (from itertools) macro and the `filter_map` method to zip up parallel arrays, filter out any rows with missing values, and package the remaining rows into an `Option<(f64,f64,f64)>` instead of `(Optional<f64>, Optional<f64>, Optional<f64>)`. 

An example:
```rust
let list1 = vec![some(1.0), some(2.0), some(3.0), none()   ];
let list2 = vec![some(4.0), some(5.0), none(),    some(6.0)];
let list3 = vec![some(7.0), none(),    some(8.0), some(9.0)];

let number_of_complete_triplets = izip!(list1, list2, list3)
    .filter_map(|opt1, opt2, opt3| {
        opt1.and_then(|val1| opt2.and_then(|val2| opt3.and_then(|val3| Some((val1,val2,val3)))))
    })
    .count();
```
This would work if `and_then` returned `Option` instead of `Optioned`. I could use `into()`, but before that I would have to implement `Noned` for `(f64,f64,f64)` and any other tuple I wanted to use it with.

As far as `or` is concerned, I agree with you about the types, but that would make kind of a weird API, where some functions returned `Option` and others returned `Optioned`. And a pattern was sort of established early in the library with `map` and `map_t`.

**Comment by rnleach** [comment]
For more discussion related to the use of `.into()`, see the discussion on issue #31.
